# Generated by Django 4.2.7 on 2024-01-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teachersmodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("subject", models.CharField(max_length=1000)),
                ("exp", models.IntegerField()),
                ("contact", models.CharField(max_length=1000)),
            ],
        ),
    ]
